# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Members',
        ),
    ]
